### ISSUE TITLE
Adiciona Mercado Sehat (Florianópolis)

### ISSUE THREAD

**Issue by silvanavlima** [LetticiaNicoli/awesome-cafezin#13]
[Site](https://mercadosehat.com.br/)
[Instagram](https://www.instagram.com/mercadosehat/)

**Comment by LetticiaNicoli** [comment]
Obrigada pela contribuição 🌹 
Adicionei nesse PR https://github.com/LetticiaNicoli/awesome-cafezin/pull/29 ☕
