### ISSUE TITLE
Adiciona o Amika CoffeeHouse (Fortaleza-CE)

### ISSUE THREAD

**Issue by herminiotorres** [LetticiaNicoli/awesome-cafezin#20]
- [site](https://amikacoffeehouse.com.br/)
- [instagram](https://www.instagram.com/amikacoffee/)
- Entrega? Brasil todo.
- Acessórios para preparo? Sim.
- Cursos? Sim.

**Comment by LetticiaNicoli** [comment]
Obrigada pela contribuição 🌹
Adicionei nesse PR #29 ☕
