### ISSUE TITLE
Adiciona HM Food Café (São Paulo)

### ISSUE THREAD

**Issue by evandrosutil** [LetticiaNicoli/awesome-cafezin#23]
[Site](https://www.hmfoodcafe.com.br/)
[Instagram](https://www.instagram.com/hmfoodcafe/?hl=pt-br)
[Entrega SP](https://hmfoodcafe.voceqpad.com.br/)

**Comment by LetticiaNicoli** [comment]
Obrigada pela contribuição 🌹
Adicionei nesse PR #29 e também no google maps ☕
