### ISSUE TITLE
Adicionar o KOF no mapa

### ISSUE THREAD

**Issue by danmalafaia** [LetticiaNicoli/awesome-cafezin#32]
https://www.google.com.br/maps/place/KOF+-+King+of+The+Fork/@-23.563755,-46.6882729,16.09z/data=!4m5!3m4!1s0x94ce579dc0010163:0x7ac8ce27038db15a!8m2!3d-23.5640823!4d-46.6837471

**Comment by LetticiaNicoli** [comment]
done!
